### PR TITLE
Fix `onWillStartSession` firing twice

### LINKED ISSUE #5714: An additional (duplicate) data explorer is opened if an editor is opened between accesses of the data frame from variables
#### Positron and OS details:

Positron Version: 2025.01.0 (Universal) build 71
OSX

#### Interpreter details:

R 4.3.3

## Describe the issue:

An additional (duplicate) data explorer is opened if an editor is opened between accesses of the data frame from variables

## Steps to reproduce the issue:

1. Data_Frame <- mtcars
2. open data frame from variables
3. create a new empty R file
4. open data from again from variables
5. note that a second data explorer opens

## Expected or desired behavior:
second access to data frame opens same tab

## Were there any error messages in the UI, Output panel, or Developer Tools console?

None

### PR DESCRIPTION
**Pull request by seeM**
Also replaced `isNew` with a more descriptive enum, `RuntimeStartMode`, and refactored the positron console service to use it. Addresses #5714.

### QA Notes

Should address #5714.

For the refactor to the console service, the console should:

1. Display `starting`/`started` when starting a runtime for the first time or switching runtimes.
2. Display `restarting`/`restarted` when restarting the active runtime, or manually shutting it down and starting it again.
3. Display `reconnecting`/`reconnected` when refreshing the window.

### CODE REVIEW

**Comment by seeM** [comment]
10x run of the failing/flaky test: https://github.com/posit-dev/positron/actions/runs/12318536435

**Comment by seeM** [comment]
10x run of the failing/flaky test: https://github.com/posit-dev/positron/actions/runs/12318984010

**Comment by seeM** [comment]
I've rebased after the upstream 1.95 merge, this is ready for review.

File: src/vs/workbench/services/positronConsole/browser/positronConsoleService.ts [hunk 1]
```diff
@@ -1281,42 +1292,33 @@ class PositronConsoleInstance extends Disposable implements IPositronConsoleInst
...
+			this.addRuntimeItem(new RuntimeItemStarting(
+				generateUuid(),
+				localize('positronConsole.starting.reconnect', "{0} reconnecting.", this._session.metadata.sessionName),
+				attachMode));
+		} else if (attachMode === SessionAttachMode.Connected) {
 			this.setState(PositronConsoleState.Ready);
 			this.addRuntimeItem(new RuntimeItemReconnected(
 				generateUuid(),
-				`${this._session.metadata.sessionName} reconnected.`
+				localize('positronConsole.starting.reconnected', "{0} reconnected.", this._session.metadata.sessionName),
```
Comment (jmcphers) [inline src/vs/workbench/services/positronConsole/browser/positronConsoleService.ts:1321]: thanks for adding loc to this!

**Review by jmcphers — DISMISSED** [review]
LGTM, and fixes the bug in my testing.
