### PR TITLE
Fix disappearing editor action bar when notebook is moved

### LINKED ISSUE #9089: Notebook: Moving a saved notebook makes it lose track of the kernel
#### Positron and OS details:

Positron Version: 2025.09.0 build 76
Code - OSS Version: 1.102.0
Commit: 3cefe92c6aa765610f0989266679e3348dbb7da1
Date: 2025-08-18T03:41:27.072Z
Electron: 35.6.0
Chromium: 134.0.6998.205
Node.js: 22.15.1
V8: 13.4.114.21-electron.0
OS: Darwin arm64 24.6.0
## Describe the issue:

Moving a previously saved notebook to a new sub-directory within the same proejct results in a restart (or new session) of the notebook kernel.

It also doesn't trigger the popup that asks whether the working directory should change.

## Steps to reproduce the issue:

1. Open a project folder
2. Create a `sub-directory`
3. Create a new notebook in the project root, and save it. 
4. Attach a Python session if necessary and assign `x = 5` in notebook session
5. Move the notebook to `/sub-directory` and try to run `x` in a new cell.
6. Get x not found error as the session is fresh.

## Expected or desired behavior:

We should reattach to the existing session and let the user know the working directory has changed.

https://github.com/posit-dev/positron/issues/9022

## Were there any error messages in the UI, Output panel, or Developer Tools console?

```
2025-08-18 18:57:32.918 [info] Python 3.13.2 (Uv: notebook-research) session 'python-notebook-22e8339d' created in /Users/thomasmock/notebook-research with command:
2025-08-18 18:57:32.918 [info] /Users/thomasmock/notebook-research/.venv/bin/python /Applications/Positron.app/Contents/Resources/app/extensions/positron-python/python_files/posit/positron_language_server.py -f {connection_file} --logfile /var/folders/dr/jx6dh4ss7cqc111rf64bxqw40000gn/T/kernel-UJeyyI/kernel.log --loglevel=error --session-mode=notebook
2025-08-18 18:57:33.271 [info] Kernel exited with code 0; cleaning up.
2025-08-18 18:57:33.271 [info] Websocket closed with kernel in status exited: {}
2025-08-18 18:57:34.409 [info] Connecting to session WebSocket via ws+unix:///var/folders/dr/jx6dh4ss7cqc111rf64bxqw40000gn/T/kc.21542.python-n.sock:/api/channels/python-notebook-22e8339d
2025-08-18 18:57:34.410 [info] Kernel is ready.
2025-08-18 18:57:34.410 [info] Starting Positron LSP server
2025-08-18 18:57:34.410 [info] Starting LSP server positron-lsp-python-d005040a for 127.0.0.1
2025-08-18 18:57:34.410 [info] Set initial console width to 71
2025-08-18 18:57:34.415 [info] Starting Positron LSP client on port 60894

##!!!! Moved file here !!!! ###
2025-08-18 18:57:56.058 [info] Shutting down
2025-08-18 18:57:56.059 [info] Stopping Positron LSP server, reason: shutting down session
2025-08-18 18:57:57.588 [info] Kernel exited with code 0; cleaning up.
2025-08-18 18:57:57.594 [info] Websocket closed with kernel in status exited: {}
2025-08-18 18:57:57.596 [info] Python 3.13.2 (Uv: notebook-research) session 'python-notebook-f5f0b568' created in /Users/thomasmock/notebook-research/notebook-subdir with command:
2025-08-18 18:57:57.596 [info] /Users/thomasmock/notebook-research/.venv/bin/python /Applications/Positron.app/Contents/Resources/app/extensions/positron-python/python_files/posit/positron_language_server.py -f {connection_file} --logfile /var/folders/dr/jx6dh4ss7cqc111rf64bxqw40000gn/T/kernel-BvtVJi/kernel.log --loglevel=error --session-mode=notebook
2025-08-18 18:57:59.039 [info] Connecting to session WebSocket via ws+unix:///var/folders/dr/jx6dh4ss7cqc111rf64bxqw40000gn/T/kc.21542.python-n.sock:/api/channels/python-notebook-f5f0b568
2025-08-18 18:57:59.040 [info] Kernel is ready.
2025-08-18 18:57:59.040 [info] Starting Positron LSP server
2025-08-18 18:57:59.040 [info] Starting LSP server positron-lsp-python-b8e2b8de for 127.0.0.1
2025-08-18 18:57:59.040 [info] Set initial console width to 71
2025-08-18 18:57:59.045 [info] Starting Positron LSP client on port 60933
```

### PR DESCRIPTION
**Pull request by dhruvisompura**
Addresses #10462

I am pretty sure that I introduced the above bug when I fixed #9089. I am pretty sure the culprit is this part here: https://github.com/posit-dev/positron/pull/10260/files#r2476066640

I thought it may have been load bearing code for #9089 but in the process of debugging #10462, I removed the code and things started working as expected. 

#### New Features

- N/A

#### Bug Fixes

- N/A

### QA Notes
See testing steps in #10462. We probably want to make sure #9089 didn't have a regression either.

@:positron-notebooks

### CODE REVIEW

File: src/vs/workbench/contrib/positronNotebook/browser/PositronNotebookEditor.tsx [hunk 1]
```diff
@@ -328,10 +328,6 @@ export class PositronNotebookEditor extends AbstractEditorWithViewState<INoteboo
 		return this._control.value;
 	}
 
-	override get scopedContextKeyService(): IContextKeyService | undefined {
-		return this.notebookInstance?.scopedContextKeyService ?? this._containerScopedContextKeyService;
-	}
-
```
Comment (dhruvisompura) [inline src/vs/workbench/contrib/positronNotebook/browser/PositronNotebookEditor.tsx:334]: Based off the errors in the dev console it looks like the reference to the scoped context key service from the notebook instance was being referenced after it had already been disposed of. 

I don't even know if we actually need this given that #9089 seems work without it and we already implement `scopedContextKeyService()` in `PositronNotebookEditor.ts`...
