### PR TITLE
Fix #11322: Better error messages when attempting to install extensions incompatible with the version of Positron

### LINKED ISSUE #11322: Error message when attempting to install an incompatible extension is misleading and incorrect
#### Positron and OS details:

```
Positron Version: 2025.10.1 build 4
Code - OSS Version: 1.103.0
Commit: b13dd1ca4803bc04a4a9165395b589b8caf4ab58
Date: 2025-10-15T00:40:32.067Z (2 mos ago)
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.2 Safari/605.1.15
```

#### Session details:

Any

## Describe the issue:

When attempting to install an extension that is not compatible with your current version of Positron due to a newer version of Positron in the `engines` field of the extension's `package.json`, e.g.:

```json
  "engines": {
    "vscode": "^1.75.0",
    "positron": "^2025.12.0"
  }
```

The error that appears is not obviously due to the version incompatibility. In Workbench, you see this:

Image

along with this:

```
2026-01-09 12:40:36.654 [error] [Window] Cannot read the extension from /home/jonathan/.positron-server/extensions/quarto.quarto-1.128.0-universal: ScanningExtension: Cannot read the extension from /home/jonathan/.positron-server/extensions/quarto.quarto-1.128.0-universal
    at ExtensionsScanner4.scanLocalExtension (file:///usr/lib/rstudio-server/bin/positron-server/out/server-main.js:28948:17)
    at async InstallExtensionInProfileTask2.doRun (file:///usr/lib/rstudio-server/bin/positron-server/out/server-main.js:29191:24)
```

Desktop, too:

Image

## Expected or desired behavior:

A dialog that says something like "This extension could not be installed because it requires Positron 2025.12.0 (you're running 2025.10.0)".

### PR DESCRIPTION
**Pull request by falbukrek**
### Summary
Addresses #11322 by adding validation of the `engines.positron` field in extension manifests to provide clear, actionable error messages when users attempt to install or update incompatible extensions. Previously, when a user tried to install an extension with `engines.positron` set to a version newer than their current Positron installation, they would see a cryptic "Cannot read the extension" error. This was misleading because it suggested the extension file was corrupted rather than incompatible.

#### 1. Enhanced Core Compatibility Function
**File:** `src/vs/platform/extensionManagement/common/abstractExtensionManagementService.ts`

- Updated `positronExtensionCompatibility()` to accept `productService` parameter for version checking. This parameter is needed in order to see the current running version of Positron.
- Integrated with `validatePositronExtensionManifest()` for version validation

#### 2. Installation Flow Updates
**File:** `src/vs/platform/extensionManagement/node/extensionManagementService.ts`

- **VSIX installations** (`installVSIX`): Validates local .vsix files before installation
- **Marketplace installations** (`installFromGallery`): Fetches and validates manifest before downloading
- **Bulk installations** (`installGalleryExtensions`): Validates all extensions in batch operations

#### 3. Update Flow Protection
- **Single updates** (`updateFromGallery`): Validates version compatibility before updating individual extensions
- **Bulk updates** (`src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts`): Enhanced "Update All Extensions" command to:
  - Capture all update operation results
  - Filter and report failures with clear messages
  - Show which specific extensions failed and why

#### 4. Test Coverage
**File:** `src/vs/platform/extensionManagement/test/common/positronExtensionCompatibility.test.ts` (new)

Added 7 test cases covering:
- ✅ Blocked extensions (existing functionality)
- ✅ Compatible version requirements
- ✅ Incompatible version requirements (newer Positron needed)
- ✅ Extensions without engine requirements (backward compatibility)
- ✅ Malformed version syntax handling
- ✅ Missing ProductService gracefully handled
- ✅ Different extension input types (basic/gallery/manifest)

#### Demonstration
The following video illustrates all the variations of this problem with the fix working correctly. (In this recording, Positron has been rigged to report version 2025.10.1 which mimics the setup reported in the original bug report)

https://github.com/user-attachments/assets/605b720f-4bc5-467d-9296-33a9d73a423a

### Release Notes
- N/A 

#### New Features
- N/A

#### Bug Fixes
- #11322 

### QA Notes

@:extensions

The demonstration video shows all the impacted use cases.  The following zip file contains the vsix files that were used for testing. 
[manual-test-extensions.zip](https://github.com/user-attachments/files/24576058/manual-test-extensions.zip)

### CODE REVIEW

**Comment by falbukrek** [comment]
I have read the CLA Document and I hereby sign the CLA

File: src/vs/workbench/services/extensionManagement/common/extensionManagementService.ts [hunk 1]
```diff
@@ -540,16 +554,17 @@ export class ExtensionManagementService extends CommontExtensionManagementServic
 	}
 
 	async installFromGallery(gallery: IGalleryExtension, installOptions?: InstallOptions, servers?: IExtensionManagementServer[]): Promise<ILocalExtension> {
+		const manifest = await this.extensionGalleryService.getManifest(gallery, CancellationToken.None);
+		if (!manifest) {
+			throw new Error(localize('Manifest is not found', "Installing Extension {0} failed: Manifest is not found.", gallery.displayName || gallery.name));
+		}
```
Comment (juliasilge) [inline src/vs/workbench/services/extensionManagement/common/extensionManagementService.ts:560]: This upstream code didn't get changed, but we moved our fenced code from before it to after it.

**Comment by juliasilge** [comment]
I kicked off some release builds here, for us to look at and test with: https://github.com/posit-dev/positron-builds/actions/runs/20941714900

**Review by juliasilge — APPROVED** [review]
Thank you so much for this contribution, including those really helpful test extensions!

This is much improved:

Image
